[build]
  publish = "."
  command = "npm run build"

# Redirecciones para el CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Redirecci칩n para acceder al panel de administraci칩n
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# Funci칩n para generar el API est치tico de eventos
[functions]
  directory = "functions"

# Comandos postprocesamiento
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 