backend:
  name: git-gateway
  branch: main # Rama en la que se harán los cambios (usa 'master' si es tu rama principal)

# Configuración de la interfaz del CMS
site_url: /
logo_url: /img/logo.png
display_url: https://shawnmendescr.netlify.app
locale: 'es'

# Personalización de la interfaz de usuario
publish_mode: editorial_workflow
media_folder: "img/uploads"
public_folder: "/img/uploads"

# Colecciones - Define los diferentes tipos de contenido que se pueden editar
collections:
  - name: "eventos" # Nombre de la colección usado internamente
    label: "Eventos" # Etiqueta visible en el panel de administración
    folder: "_eventos" # Carpeta donde se guardarán los archivos
    create: true # Permitir a los usuarios crear nuevas entradas
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Plantilla para nombres de archivo
    fields: # Los campos que se mostrarán en el editor
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha del Evento", name: "date", widget: "datetime"}
      - {label: "Ubicación", name: "location", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Imagen", name: "image", widget: "image", required: false}
      - {label: "Enlace de Registro", name: "registrationLink", widget: "string", required: false}
      - {label: "Destacado", name: "featured", widget: "boolean", default: false}
      
  - name: "configuracion"
    label: "Configuración"
    files:
      - label: "Información General"
        name: "general"
        file: "_data/general.json"
        fields:
          - {label: "Nombre del Sitio", name: "siteName", widget: "string"}
          - {label: "Descripción del Sitio", name: "siteDescription", widget: "text"}
          - label: "Redes Sociales"
            name: "socialMedia"
            widget: "list"
            fields:
              - {label: "Plataforma", name: "platform", widget: "select", options: ["Facebook", "Instagram", "Twitter", "TikTok", "YouTube"]}
              - {label: "URL", name: "url", widget: "string"}
          - {label: "Correo de Contacto", name: "contactEmail", widget: "string"} 