backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "eventos"
    label: "Eventos"
    folder: "_eventos"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Ubicación", name: "location", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"} 